name: Java CI with Maven

on:
  [push, pull_request]

jobs:
  dock-comp-test:
    strategy:
      matrix:
        splunk-version:
          - latest
          - 8.0
    runs-on: ubuntu-latest
    container: maven:3-jdk-8
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up make
        run: sudo apt-get -y install make
      - name: Make Up
        run: make up
      - name: Make Test
        run: make test
        env:
          SPLUNK_PASSWORD: changed!
          SPLUNK_HOST: splunk
